events {}
http {
  server {
    listen 443 ssl;
    ssl_protocols TLSv1.3;
    ssl_certificate     /chains/classical/fullchain.crt;
    ssl_certificate_key /chains/classical/leaf.key;
    ssl_certificate     /chains/pq/fullchain.crt;
    ssl_certificate_key /chains/pq/leaf.key;
    location / { return 200 "ok"; }
  }
}
